language: node_js
node_js:
  - lts/*
notifications:
  email:
    on_success: change
    on_failure: always
script:
  - npm test
deploy:
  - provider: script
    skip_cleanup: true
    script: npm run _version
    on:
      branch: master
      repo: smockle/homebridge-harmony-tv
      tags: false
  - provider: npm
    skip_cleanup: true
    email: bot@smockle.com
    api_key:
      secure: Q34yuh7Xs7YTlT5sfyLc8wH+GFykmJWZjnGD1wyxgCVBDo5xA6ix5HWovksdNmjr7QtMD9NOBE1n77n/HB4lwQ+MKW/ygYGkYtJ9PmFMNOkBF3pubwZC0KyR59Tsx7ispq/EWgBV9HBNtBGYfKfiZVfb81vvv2Oc6QH8Y8RztvlUj1pGowBdDiJ+xcOz47OKN+m7fpweB/GToDSklE3Vuq3SkNm3kEUsfx4wcH0h8B8LPzNWb+uQE+UzV//+85GRwzhHZNc+gPvHKbbEkeb0Rr94wD9pMlN/ZUUToN4MFFJK1vsPVt+XXbdv6iPJMSLxxZtJqI4kI+1FjUB68iRH03A1G+0S14mwvuufltrMI7e843WbXkUf8lwro2C2PeqJ+YS/Ukax4kxGWOAh1iN32bE78IxfNUDqLXm6r+CMlTS/+7uHvAsWHOF2WXyoX6Yc+1O8nYOsoyABNGJQScxF98pW7LNOy1BaLHQ9VqXb7dFzSm0dJ9bRFyM0cyp9tux8ZxflHzFwlvqmV5wAoUnMpuFnDFLvtMNQbER2qujNFzHbxb8NFW66VpiqDpyjpzHqrnsSrUWGWTUbigwKXvZuEtvJeJ6MKlaztWUMPFmWudsJgA0RXkb+2il9FDv+xyYKuCwPcGn53mbsHREAuGKDybOYulwEh3ivGTvttILgVDI=
    on:
      branch: master
      repo: smockle/homebridge-harmony-tv
      tags: false
