language: node_js
node_js:
  - lts/*
notifications:
  email:
    on_success: change
    on_failure: change
script:
  - npm test
deploy:
  - provider: script
    skip_cleanup: true
    script: npm run _version
    on:
      branch: master
      repo: smockle/homebridge-harmony-tv
      tags: false
  - provider: npm
    skip_cleanup: true
    email: bot@smockle.com
    api_key:
      secure: Y7DwHc+VX0aLNnQvyZVxk/YbVAZdl8Plg/zaVC/dBdmJ1VOgdgp2LIorGMe926bm4BBdj8S89Kiit38YGZk9xFjtzpS2IuJWTBIFmvkNA9F3gSEn20Efykb2LTd0pmLixB5VaMhiw6iCCwnHjVasQ8pk6kpEBGXMhCAvKmVCCYmXukKCORto3r52SlU7oLKc6QapwvT8aqJNyClg37XYmV00vM8peR/BTXIqMO6sse3Ez4FOXH6hgvr36awIGRNwqUh4JkOZAjGybyUxTOFS904PlsGgLIKdHphJ3bbkqat7k0M5SUmIUHNxqWxqVow1omHKI4IqN8owHtrRQCviecElFTaRUKJ7EBIHExr7svDDAdHpIfAEVh+HtR54SYp+3EzsvgV94AdK3ZpqILt80+gOkvagSRTlCgsbtFqDQtpofWujYo6M62e0onb2B7bFLQ8xgKB4ihLX0Oaol7DgmaX2ttOGUq1QyvMHJBgJ+Pk/9/MlhbaUjpAgz3BqHejiwWvS6FvMwyiEgqDX46fwUaxtXckoDfQtFZEIFx9ZGLwiYIJe8kcAeRrotNYgOp7a+Bq5orKsdMPMZ1eDsGwZfFJn2M57KmytgZbuMoiKgpkbk2zVc81rknxxAF1kg2FQcfLhtkyecDiNn1K4fDelINGGyGMCvnaQnXCWyaTrR5s=
    on:
      branch: master
      repo: smockle/homebridge-harmony-tv
      tags: false
