name: Publish
on:
  push:
    branches: ["master"]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Get sources
        if: contains(github.event.commits[0].message, '[skip ci]') == false
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Setup Node.js (npm)
        if: contains(github.event.commits[0].message, '[skip ci]') == false
        uses: "actions/setup-node@v1"
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"

      - name: Bump version
        if: contains(github.event.commits[0].message, '[skip ci]') == false
        uses: "smockle/action-version@master"
        env:
          GITHUB_USER_EMAIL: bot@smockle.com
          GITHUB_USER_NAME: smockle-bot
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}

      - name: Publish (npm)
        if: contains(github.event.commits[0].message, '[skip ci]') == false
        run: "yarn publish --access public --registry=https://registry.npmjs.org/"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
